### ISSUE TITLE
PiT result: migrating a vaadin starter project from V20 to V21 fails with missing dependencies and compilation errors

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/fusion#52]
Migrating a vaadin starter project from V20 to V21 with the migration guide (updating `pom.xml` and deleting `node_modules` folder, `package.json`, and `pnpm-lock.yaml` and updating the imports in ts files) leads to the following error message (https://drive.google.com/open?id=1WGfrKD4fyc4daGd7dpdgb1U3pyB83ghN)

A couple of imports seems to be missed in package.json file, like:

```json
"@adobe/lit-mobx": "2.0.0-rc.4",
"lumo-css-framework": "^4.0.10",
"mobx": "^6.1.5"
```

This ticket was created as the result of a test run during the Platform in Test. The full report can be found [here](https://docs.google.com/document/d/1fDdsPfzZIDuYBs6DbW2uiWgZLCUSHBnGACDqMUKCosE).

**Comment by Artur-** [comment]
Don't delete `package.json`

**Comment by gilberto-torrezan** [comment]
Note: we have a report mentioning that this exact same problem is also happening when migrating Fusion apps from V19 to V20.
